name: Tagged release

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Tests to succeed
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-test
        with:
          token: ${{ secrets.PA_TOKEN }}
          checkName: Test
          ref: ${{ github.sha }}
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build redtape
        run: uv build
      - name: Get latest tag
        id: latest
        uses: WyriHaximus/github-action-get-previous-tag@v1.2.0
      - name: Release new SemVer tag
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PA_TOKEN }}"
          prerelease: false
          files: |
            dist/*.tar.gz
            dist/*.whl
        id: automatic_releases
